# Utility used to parse the request needed by the API
# to post a new information demand
class RequestParser

  # Parses the information using the info_request and outgoing_message objects
  def self.parse(info_request, outgoing_message)
    @req = Hash.new
    add_info_request_attrs(info_request)
    add_outgoing_message_attrs(outgoing_message)
    add_default_values
    @req
  end

  def self.add_outgoing_message_attrs(outgoing_message)
    @req['descripcion'] = outgoing_message.body
  end

  def self.add_info_request_attrs(info_request)
    @req['titulo'] = info_request.title
    @req['nombre'] = info_request.user.name
    @req['mail'] = info_request.incoming_email # Magic email generated by QueremoSaber
    @req['apellido'] = info_request.user.surname
    @req['domicilio'] = info_request.user.address
    @req['nacionalidad'] = info_request.user.nationality
    @req['institucionID'] = info_request.public_body.id_gov
  end

  def self.add_default_values
    @req['distritoID'] = 1 # Default value
    @req['tipoRespuestaID'] = 1 # Via email
    @req['formatoID'] = 0 # None of the available
    @req['soporteID'] = 2 # Digital Media

    # Non obligatory according to
    # http://informacionpublica.paraguay.gov.py/portal/#!/hacer_solicitud#busqueda
    @req['telefono'] = '+595212179000'
    @req['sexo'] = ''
    @req['fechaNacimiento'] = ''
  end

end